devproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum.urls', namespace='forum')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

# Use static file server for static and media files (debug only)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path

from forum import views
from forum.core.feeds import LastPosts, LastTopics, LastPostsOnForum

app_name = 'forum'

urlpatterns = [
    path('', views.index, name='index'),
    path('forum/<int:forum_id>/', views.show_forum, name='forum'),

    # Topic
    path('forum/<int:forum_id>/topic/create', views.add_topic, name='add_topic'),

    # User
    path('user/<username>/essentials/', views.user, name='forum_profile_essentials'),
    path('user/<username>/', views.user, name='forum_profile'),
    path('users/', views.users, name='forum_users'),

    # Feeds
    path('feeds/posts/', LastPosts(), name='forum_posts_feed'),
    path('feeds/topics/', LastTopics(), name='forum_topics_feed'),
    path('feeds/forum/<int:forum_id>/', LastPostsOnForum(), name='forum_forum_feed'),

    # Posts
    path('preview/', views.post_preview, name='post_preview')
]

forum/models/category.py
from django.contrib.auth.models import Group
from django.db import models


class Category(models.Model):
    name = models.CharField('Name', max_length=80)
    groups = models.ManyToManyField(Group, blank=True, verbose_name='Groups')
    position = models.IntegerField('Position', blank=True, default=0)

    class Meta:
        db_table = 'categories'
        ordering = ['position']
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def forum_count(self):
        return self.forums.all().count()

    def has_access(self, user):
        if user.is_superuser:
            return True
        if self.groups.exists():
            if user.is_authenticated:
                if not self.groups.filter(user__pk=user.id).exists():
                    return False
            else:
                return False
        return True

forum/models/forum.py
from django.db import models
from django.urls import reverse

from ..core.conf import settings
from ..core.fields import ExtendedImageField
from ..models.post import Post


class Forum(models.Model):
    category = models.ForeignKey('forum.Category', related_name='forums', verbose_name='Category',
                                 on_delete=models.CASCADE)
    name = models.CharField('Name', max_length=80)
    position = models.IntegerField('Position', blank=True, default=0)
    description = models.TextField('Description', blank=True, default='')
    moderators = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, verbose_name='Moderators')
    updated = models.DateTimeField('Updated', auto_now=True)
    post_count = models.IntegerField('Post count', blank=True, default=0)
    topic_count = models.IntegerField('Topic count', blank=True, default=0)
    last_post = models.ForeignKey('Post', related_name='last_forum_post', blank=True, null=True,
                                  on_delete=models.CASCADE)
    forum_logo = ExtendedImageField('Forum Logo', blank=True, default='',
                                    upload_to=settings.FORUM_LOGO_UPLOAD_TO,
                                    width=settings.FORUM_LOGO_WIDTH,
                                    height=settings.FORUM_LOGO_HEIGHT)

    class Meta:
        db_table = 'forums'
        ordering = ['position']
        verbose_name = 'Forum'
        verbose_name_plural = 'Forums'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('forum:forum', args=[self.id])

    @property
    def posts(self):
        return Post.objects.filter(topic__forum__id=self.id).select_related()

forum/forms.py
from datetime import timedelta

from django import forms
from django.utils import timezone

from forum.core.conf import settings
from forum.core.utils import set_language
from forum.models import Profile, Post, Poll, PollChoice

SORT_USER_BY_CHOICES = (
    ('username', 'Username'),
    ('registered', 'Registered'),
    ('num_posts', 'No. of posts'),
)

SORT_DIR_CHOICES = (
    ('ASC', 'Ascending'),
    ('DESC', 'Descending'),
)


class EssentialsProfileForm(forms.ModelForm):
    username = forms.CharField(label='Username')
    email = forms.CharField(label='Email')

    class Meta:
        model = Profile
        fields = ['auto_subscribe', 'time_zone', 'language']

    def __init__(self, *args, **kwargs):
        extra_args = kwargs.pop('extra_args', {})
        self.request = extra_args.pop('request', None)
        self.profile = kwargs['instance']
        super().__init__(*args, **kwargs)
        self.fields['username'].initial = self.profile.user.username
        if not self.request.user.is_superuser:
            self.fields['username'].widget = forms.HiddenInput()
        self.fields['email'].initial = self.profile.user.email

    def save(self, commit=True):
        if self.cleaned_data:
            if self.request.user.is_superuser:
                self.profile.user.username = self.cleaned_data['username']
            self.profile.user.email = self.cleaned_data['email']
            self.profile.time_zone = self.cleaned_data['time_zone']
            self.profile.language = self.cleaned_data['language']
            self.profile.user.save()
            if commit:
                self.profile.save()
        set_language(self.request, self.profile.language)
        return self.profile


class PollForm(forms.ModelForm):
    question = forms.CharField(label='Question')
    answers = forms.CharField(label='Answers', min_length=2, widget=forms.Textarea,
                              help_text='Write each answer on a new line')
    days = forms.IntegerField(label='Days', required=False, min_value=1,
                              help_text='Number of days for this poll to run. Leave empty for never ending poll')
    choice_count = forms.IntegerField(label='Choice Count', required=True, initial=1, min_value=1,
                                      error_messages={'min_value': "Number of choices must be positive."})

    class Meta:
        model = Poll
        fields = ['question', 'choice_count']

    def has_data(self):
        return any(self.data.get(key) for key in ('question', 'answers', 'days'))

    # def clean_answers(self):
    #     raw_answers = self.cleaned_data['answers']
    #     answers = [answer.strip() for answer in raw_answers.splitlines() if answer.strip()]
    #     if answers:
    #         raise forms.ValidationError('There is no valid answer!')
    #
    #     is_max_length = max([len(answer) for answer in answers])
    #     should_max_length = PollChoice._meta.get_field('choice').max_length
    #     if is_max_length > should_max_length:
    #         raise forms.ValidationError('One of this answers are too long')
    #
    #     return answers

    def save(self, post):
        poll = super().save(commit=False)
        poll.topic = post.topic
        days = self.cleaned_data['days']
        if days:
            poll.deactivate_date = timezone.now() + timedelta(days=days)
        poll.save()
        answers = self.cleaned_data['answers']
        for answer in answers:
            PollChoice.objects.create(poll=poll, choice=answer)


class AddPostForm(forms.ModelForm):
    form_name = 'AddPostForm'

    name = forms.CharField(label='Subject', max_length=255, widget=forms.TextInput(attrs={'size': '115'}))
    attachment = forms.FileField(label='Attachment', required=False)
    subscribe = forms.BooleanField(label='Subscribe', help_text='Subscribe this topic', required=False)

    class Meta:
        model = Post
        fields = ['body']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.topic = kwargs.pop('topic', None)
        self.forum = kwargs.pop('forum', None)
        self.ip = kwargs.pop('ip', None)
        super().__init__(*args, **kwargs)

        if self.topic:
            self.fields['name'].widget = forms.HiddenInput()
            self.fields['name'].required = False

        self.fields['body'].widget = forms.Textarea(attrs={'class': 'markup', 'rows': '20', 'cols': '95'})

    def clean(self):
        error_msg = 'Can\'t be empty nor contain only whitespace characters'
        cleaned_data = self.cleaned_data
        body = cleaned_data.get('body')
        subject = cleaned_data.get('name')
        if subject:
            if not subject.strip():
                self._errors['name'] = self.error_class([error_msg])
                del cleaned_data['name']
        if body:
            if not body.strip():
                self._errors['body'] = self.error_class([error_msg])
                del cleaned_data['body']
        return cleaned_data

    def save(self):
        if self.


class UserSearchForm(forms.Form):
    username = forms.CharField(required=False, label='Username')
    sort_by = forms.ChoiceField(choices=SORT_USER_BY_CHOICES, label='Sort by')
    sort_dir = forms.ChoiceField(choices=SORT_DIR_CHOICES, label='Sort Order')

    def filter(self, qs):
        if self.is_valid():
            username = self.cleaned_data['username']
            sort_by = self.cleaned_data['sort_by']
            sort_dir = self.cleaned_data['sort_dir']
            qs = qs.filter(username__contains=username, forum_profile__post_count__gte=settings.POST_USER_SEARCH)
            if sort_by == 'username':
                if sort_dir == 'ASC':
                    return qs.order_by('username')
                elif sort_dir == 'DESC':
                    return qs.order_by('-username')
            elif sort_by == 'registered':
                if sort_dir == 'ASC':
                    return qs.order_by('date_joined')
                elif sort_dir == 'DESC':
                    return qs.order_by('-date_joined')
            elif sort_by == 'num_posts':
                if sort_dir == 'ASC':
                    return qs.order_by('forum_profile__post_count')
                elif sort_dir == 'DESC':
                    return qs.order_by('-forum_profile__post_count')
        else:
            return qs

forum/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from .core.conf import settings
from .core.utils import convert_text_to_html, smiles, get_page, build_form
from .forms import EssentialsProfileForm, UserSearchForm, AddPostForm, PollForm
from .models import Forum, Post, Category, Topic

User = get_user_model()


def index(request):
    users_cached = cache.get('forum_users_online', {})
    users_online = users_cached and User.objects.filter(id__in=users_cached.keys()) or []
    guests_cached = cache.get('forum_guests_online', {})
    guests_count = len(guests_cached)
    users_count = len(users_online)

    forums = Forum.objects.all()
    user = request.user
    if not user.is_superuser:
        user_groups = user.groups.all() or []
        forums = forums.filter(Q(category__groups__in=user_groups) | Q(category__groups__isnull=True))
    forums = forums.select_related('last_post__topic', 'last_post__user', 'category')

    categories = {}
    forum_dict = {}
    for forum in forums:
        category = categories.setdefault(forum.category.id,
                                         {'id': forum.category.id, 'category': forum.category, 'forums': []})

        category['forums'].append(forum)
        forum_dict[forum.id] = forum

    categories = sorted(categories.values(), key=lambda x: x['category'].position)

    context = {
        'categories': categories,
        'posts': Post.objects.count(),
        'topics': Topic.objects.count(),
        'users': User.objects.count(),
        'users_online': users_online,
        'online_count': users_count,
        'guest_count': guests_count,
        'last_user': User.objects.latest('date_joined')
    }
    return render(request, 'forum/index.html', context)


def show_forum(request, forum_id):
    forum = get_object_or_404(Forum, pk=forum_id)
    if not forum.category.has_access(request.user):
        raise PermissionDenied
    topics = forum.topics.order_by('-sticky', '-updated').select_related()
    moderator = request.user.is_superuser or request.user in forum.moderators.all()

    categories = []
    for category in Category.objects.all():
        if category.has_access(request.user):
            categories.append(category)

    context = {
        'categories': categories,
        'forum': forum,
        'posts': forum.post_count,
        'topics_page': get_page(topics, request, settings.FORUM_PAGE_SIZE),
        'moderator': moderator
    }

    return render(request, 'forum/forum.html', context)


@login_required
def add_topic(request, forum_id):
    forum = get_object_or_404(Forum, pk=forum_id)
    if not forum.category.has_access(request.user):
        raise PermissionDenied

    ip = request.META.get('REMOTE_ADDR', None)
    post_form_kwargs = {'forum': forum, 'user': request.user, 'ip': ip}

    poll_form = None
    if request.method == 'POST':
        form = AddPostForm(request.POST, request.FILES, **post_form_kwargs)
        if form.is_valid():
            all_valid = True
        else:
            all_valid = False

        if settings.ENABLE_POLLS:
            poll_form = PollForm(request.POST)
            if not poll_form.has_data():
                poll_form = PollForm()
            elif not poll_form.is_valid():
                all_valid = False

        if all_valid:
            post = form.save()
            if poll_form and poll_form.has_data():
                poll_form.save(post)
                messages.success(request, 'Topic with poll saved')
            else:
                messages.success(request, 'Topic saved')
            return redirect(post.get_absolute_url())
    else:
        form = AddPostForm(
            initial={
                'markup': request.user.forum_profile.markup,
                'subscribe': request.user.forum_profile.auto_subscribe
            },
            **post_form_kwargs
        )
        if settings.ENABLE_POLLS and forum_id:
            poll_form = PollForm()
    context = {
        'forum': forum,
        'create_poll_form': poll_form,
        'form': form,
        'form_url': request.path,
        'back_url': forum.get_absolute_url()
    }

    return render(request, 'forum/add_topic.html', context)


def user(request, username, section='essentials'):
    form_class = EssentialsProfileForm
    template = 'forum/profile/profile_essentials.html'
    _user = get_object_or_404(User, username=username)
    if request.user.is_authenticated and _user == request.user or request.user.is_superuser:
        form = build_form(form_class, request, instance=_user.forum_profile, extra_args={'request': request})
        if request.method == 'POST' and form.is_valid():
            form.save()
            profile_url = reverse(f'forum:forum_profile_{section}', args=[_user.username])
            messages.success(request, 'User profile saved.')
            return redirect(profile_url)

        context = {'active_menu': section, 'profile': _user, 'form': form}
        return render(request, template, context)

    else:
        template = 'forum/user.html'
        topic_count = Topic.objects.filter(user__id=_user.id).count()
        if _user.forum_profile.post_count < settings.POST_USER_SEARCH and not request.user.is_authenticated:
            messages.error(request, 'Please sign in.')
            return redirect(settings.LOGIN_URL + f'?next={request.path}')

        context = {'profile': user, 'topic_count': topic_count}
        return render(request, template, context, context)


def users(request):
    _users = User.objects.filter(forum_profile__post_count__gte=settings.POST_USER_SEARCH).order_by('username')
    form = UserSearchForm(request.GET)
    _users = form.filter(_users)
    context = {'users_page': get_page(_users, request, settings.USERS_PAGE_SIZE), 'form': form}
    return render(request, 'forum/users.html', context)


def post_preview(request):
    """Preview for markitup"""

    markup = request.user.forum_profile.markup
    data = request.POST.get('data', '')

    data = convert_text_to_html(data, markup)
    if settings.SMILES_SUPPORT:
        data = smiles(data)
    context = {'data': data}
    return render(request, 'forum/post_preview.html', context)

forum/templates/forum/add_topic.html
{% extends 'forum/base.html' %}
{% load forum_extras i18n %}

{% block content %}
  <div class="linkst">
    <div class="inbox">
      {% if forum %}
        <ul class="start">
          <li><a href="{% url 'forum:index' %}">{% trans "Root" %}</a></li>
          <li>&raquo; {% link forum %}</li>
        </ul>
      {% else %}
        <ul>
          <li><a href="{% url 'forum:index' %}">{% trans "Root" %}</a></li>
          <li>&raquo; {% link topic.forum %}</li>
          <li>&raquo; {{ topic }}</li>
        </ul>
      {% endif %}
      <div class="clearer"></div>
    </div>
  </div>
  {% include "forum/includes/post_form.html" %}
{% endblock %}

forum/templates/forum/base.html
{% load static forum_extras i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}{% endblock %} {{ forum_settings.FORUM_BASE_TITLE }}</title>
  <meta name="description" content="{{ forum_settings.FORUM_META_DESCRIPTION }} "/>
  <meta name="keywords" content="{{ forum_settings.FORUM_META_KEYWORDS }}"/>
  <meta http-equiv="content-type" content="text/html; charset=utf-8"/>

  {% set_theme_style user %}

  <link rel="alternate" type="application/atom+xml" href="{% url 'forum:forum_posts_feed' %}"
        title="{% trans "Latest posts on forum" %}"/>
  <link rel="alternate" type="application/atom+xml" href="{% url 'forum:forum_topics_feed' %}"
        title="{% trans "Latest topics on forum" %}"/>

  <link rel="shortcut icon" href="{% static 'forum/favicon.png' %}" type="image/png"/>

  <script>
    var STATIC_URL = "{{ STATIC_URL }}";
    var POST_PREVIEW_URL = "{% url 'forum:post_preview' %}";
  </script>

  <script src="{{ forum_settings.JQUERY_URL }}"></script>

  {% if user.is_authenticated %}
    {% if post %}
      {% with markup=post.markup %}
        {% include "forum/includes/markup_editor.html" %}
      {% endwith %}
    {% else %}
      {% with markup=user.forum_profile.markup %}
        {% include "forum/includes/markup_editor.html" %}
      {% endwith %}
    {% endif %}

    <script>
      $(document).ready(function () {
        $(".markup").markItUp(mySettings);
      });
    </script>

  {% endif %}

  <!-- Highlightjs goodies -->
  <link rel="stylesheet" href="{% static 'forum/css/pygments.css' %}"/>
  {% if highlight_word %}

    <script src="{% static 'forum/js/jquery.highlight-3.pack.js' %}"></script>

    <script>
      $(document).ready(function () {
        $("div.postmsg").highlight("{{ highlight_word }}");
      });
    </script>

  {% endif %}
  {% block extra_meta %}{% endblock %}
</head>
<body>
{% include 'forum/header.html' %}

{% block messages %}
  {% if messages %}
    <div id="messages" class="block">
      <h2><span>{% trans "Notice" %}</span></h2>
      <div class="box">
        <div class="inbox">
          <ul class="messagelist">
            {% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock messages %}

{% block pre_content %}{% endblock %}
{% block content %}{% endblock %}
{% block post_content %}{% endblock %}
<div id="brdfooter" class="block">
  <h2><span>{% trans "Board footer" %}</span></h2>
  <div class="box">
    <div class="inbox">
      {% block controls %}
        <dl id="searchlinks" class="conl">
          <dt><strong>{% trans "Search links" %}</strong></dt>
          <dd><a href="">{% trans "Show recent posts" %}</a></dd>
          <dd>
            <a href="">{% trans "Show unanswered posts" %}</a>
          </dd>
          {% if user.is_authenticated %}
            <dd>
              <a href="">{% trans "Show your subscribed topics" %}</a>
            </dd>
            <dd>{% trans "Show your" %} <a
              href="">{% trans "topics" %}</a>/<a
              href="">{% trans "posts" %}</a>
            </dd>
          {% endif %}
        </dl>
      {% endblock controls %}
      <p class="conr">Powered by <a href="http://djangobb.org/">DjangoBB</a></p>
      <div class="clearer"></div>
    </div>
  </div>
</div>
</body>
</html>

forum/templates/forum/forum.html
{% extends 'forum/base.html' %}
{% load static %}
{% load forum_extras i18n %}

{% block title %}{{ forum.name }} / {% endblock %}
{% block content %}
  <div class="linkst">
    <div class="inbox">
      <div
        class="pagelink conl">{% include 'forum/paginator.html' with page=topics_page request=request only %}</div>
      {% if user.is_authenticated %}
        <p class="postlink conr"><a href="{% url 'forum:add_topic' forum.id %}">{% trans "New topic" %}</a></p>
      {% endif %}
      <ul>
        <li><a href="{% url 'forum:index' %}">{% trans "Root" %}</a></li>
        <li>&raquo; {{ forum.name }}</li>
      </ul>
      <div class="clearer"></div>
    </div>
  </div>
  <div id="vf" class="blocktable">
    <h2>
      <a href="{% url 'forum:forum_forum_feed' forum.id %}"><img
        src="{% static 'forum/img/feed-icon-small.png' %}" alt="[RSS Feed]" title="[RSS Feed]"
        class="rss"/></a>
      <b><span>{{ forum.name }}</span></b>
    </h2>
    <div class="box">
      <div class="inbox">
        <table>
          <thead>
          <tr>
            <th class="tcl" scope="col">{% trans "Topic" %}</th>
            <th class="tc2" scope="col">{% trans "Replies" %}</th>
            <th class="tc3" scope="col">{% trans "Views" %}</th>
            <th class="tcr" scope="col">{% trans "Last post" %}</th>
          </tr>
          </thead>
          <tbody>
          {% for topic in topics_page %}
            <tr>
              <td class="tcl">
                <div class="intd">
                  <div {% if topic.sticky %}class="sticky"{% else %}{% if topic.closed %}class="closed"
                       {% else %}{% if topic|has_unreads:user %}class="inew"
                       {% else %}class="icon"{% endif %}{% endif %}{% endif %}>
                    <div class="nosize"><!-- --></div>
                  </div>
                  <div class="tclcon">
                    {% if topic.sticky %}
                      {% trans "Sticky:" %}
                    {% endif %}
                    {% if topic|has_unreads:user %}
                      <strong>{% link topic %} <span
                        class="byuser">{% trans "by" %} {{ topic.user.username }}</span></strong>
                    {% else %}
                      {% link topic %} <span class="byuser">{% trans "by" %} {{ topic.user.username }}</span>
                    {% endif %}
                  </div>
                </div>
              </td>
              <td class="tc2">{{ topic.reply_count }}</td>
              <td class="tc3">{{ topic.views }}</td>
              <td class="tcr"><a href="{{ topic.last_post.get_absolute_url }}">{% forum_time topic.updated %}</a> <span
                class="byuser">{% trans "by" %} {{ topic.last_post.user.username }}</span></td>
            </tr>
          {% empty %}
            <tr>
              <td class="djangobbcon1" colspan="4">{% trans "Forum is empty." %}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="linkst">
    <div class="inbox">
      <div
        class="pagelink conl">{% include 'forum/paginator.html' with page=topics_page request=request only %}</div>
      {% if user.is_authenticated %}
        <p class="postlink conr"><a href="">{% trans "New topic" %}</a></p>
      {% endif %}
      <ul>
        <li><a href="{% url 'forum:index' %}">{% trans "Root" %}</a></li>
        <li>&raquo; {{ forum.name }}</li>
      </ul>
      <div class="clearer"></div>
    </div>
  </div>
{% endblock %}
{% block controls %}
  <div class="conl">
    <form id="qjump" method="get" action="forum">
      <div><label>{% trans "Jump to" %}
        <br/>
        <select name="id" id="forum_id"
                onchange="window.location=('{% url 'forum:index' %}'+this.options[this.selectedIndex].value)">
          {% for category in categories %}
            <optgroup label="{{ category }}">
              {% for forum in category.forums.all %}
                <option value="{{ forum.id }}">{{ forum.name }}</option>
              {% endfor %}
            </optgroup>
          {% endfor %}
        </select>
        <input type="button" onclick="window.location=('{% url 'forum:index' %}'+getElementById('forum_id').value)"
               value=" {% trans "Go" %} " accesskey="g"/>
      </label></div>
    </form>
    {% if moderator %}
      <p id="modcontrols"><a href="">{% trans "Moderate forum" %}</a></p>
    {% endif %}
  </div>
{% endblock %}

{% block lofi %}
  {% if forum_settings.LOFI_SUPPORT %}
    <p class="lofi">
      <a href="{{ forum.get_absolute_url }}lofi/">Lo-Fi Version</a>
    </p>
  {% endif %}
{% endblock %}

forum/templates/forum/header.html
{% load forum_extras i18n%}

<div id="djangobbwrap">
  <div id="djangobbindex" class="djangobb">
    <div id="brdheader" class="block">
      <div class="box">
        <div id="brdtitle" class="inbox">
          <h1><span><a href="">{{ forum_settings.HEADER|safe }}</a></span></h1>
          <p><span>{{ forum_settings.TAGLINE|safe }}</span></p>
        </div>
        <div id="brdmenu" class="inbox">
          <ul>
            {% block menu %}
              <li id="navindex"><a href="{% url 'forum:index' %}">{% trans "Index" %}</a></li>
              <li id="navuserlist"><a href="{% url 'forum:forum_users' %}">{% trans "User list" %}</a></li>
              <li id="navsearch"><a href="">{% trans "Search" %}</a></li>
              {% if user.is_superuser %}
                <li id="navadmin"><a href="{% url 'admin:index' %}">{% trans "Administration" %}</a></li>
              {% endif %}
              {% if user.is_authenticated %}
                <li id="navprofile"><a href="{% url 'forum:forum_profile' user.username %}">{% trans "Profile" %}</a>
                </li>
                {% if forum_settings.PM_SUPPORT %}
                  <li id="navpm"><a href="{% url 'messages_inbox' %}">{% trans "PM" %}</a></li>
                {% endif %}
              {% endif %}
            {% endblock %}
          </ul>
        </div>
        <div id="brdwelcome" class="inbox">
          <ul class="conl">
            {% if user.is_authenticated %}
              <li>{% trans "Logged in as" %} <strong>{{ user.username }}</strong></li>
              <li>{% trans "Last visit:" %} {% forum_time user.last_login %}</li>
              {% if forum_settings.PM_SUPPORT and messages_inbox_count > 0 %}
                <ul>
                  <li class="pmlink"><strong><a href="{% url 'messages_inbox' %}">{% trans "There are new messages" %}
                    ({{ messages_inbox_count }})</a></strong></li>
                </ul>
              {% endif %}
            {% else %}
              <li>{% trans "You are not logged in." %}</li>
            {% endif %}
            {% if user.is_superuser and reports %}
              <li class="reportlink"><strong><a href="{% url 'admin:index' %}">{% trans "There are new reports" %}
                ({% new_reports %})</a></strong></li>
            {% endif %}
          </ul>
          {% if user.is_authenticated %}
            <ul class="conr">
              <li><a
                href="">{% trans "Show new posts since last visit" %}</a>
              </li>
              <li><a href="">{% trans "Mark all topics as read" %}</a></li>
            </ul>
          {% endif %}
          <div class="clearer"></div>
        </div>
      </div>
    </div>

    {% if forum_settings.NOTICE %}
      <div id="announce" class="block">
        <h2><span>{% trans "Notice" %}</span></h2>
        <div class="box">
          <div class="inbox">
            <div>{{ forum_settings.NOTICE|safe }}</div>
          </div>
        </div>
      </div>
    {% endif %}

forum/templates/forum/paginator.html
{% load i18n forum_extras %}

{% if page.has_other_pages %}
  {% trans "Pages" %}:
  {% if page.has_previous %}
    <a href="?{% url_replace request 'page' page.previous_page_number %}">&laquo;</a>
  {% endif %}
  {% for number in page.paginator.page_range %}
    {% if number == page.number %}
      <strong>{{ number }}</strong>
    {% else %}
      <a href="?{% url_replace request 'page' number %}">{{ number }}</a>
    {% endif %}
  {% endfor %}
  {% if page.has_next %}
    <a href="?{% url_replace request 'page' page.next_page_number %}">&raquo;</a>
  {% endif %}
{% endif %}

forum/templates/forum/post_preview.html
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'forum/css/pygments.css' %}"/>
</head>
<body>
{{ data|safe }}
</body>